"""Regenerate CALENDAR.md and RECORDING.md from the post.md files, and check them.

Run from the repo root:  python3 content/build_calendar.py
"""
import datetime as dt
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
START = dt.date(2026, 9, 28)
REQUIRED = ["## Caption", "## Hashtags", "## First comment"]

posts, errors = [], []
for folder in ROOT.iterdir():
    if not (folder / "post.md").exists():
        continue
    m = re.match(r"(\w+) (\d+) - (\w+) - (.+)", folder.name)
    date = dt.datetime.strptime(f"{m[1]} {m[2]} 2026", "%B %d %Y").date()
    if date.strftime("%A") != m[3]:
        errors.append(f"{folder.name}: weekday should be {date:%A}")
    text = (folder / "post.md").read_text()
    for h in REQUIRED:
        if f"\n{h}\n" not in text:
            errors.append(f"{folder.name}: missing '{h}'")
    meta = re.search(r"\*\*Format:\*\* (.+?) · \*\*Series:\*\* (.+?) · \*\*CTA:\*\* (.+?) ·", text)
    needs = re.search(r"\*\*Needs:\*\* (.+)", text)
    todo = re.findall(r"- \[ \] (.+)", text.split("## 🎥 What you need to do")[1].split("\n## ")[0]) if "## 🎥 What you need to do" in text else []
    posts.append(dict(date=date, folder=folder.name, title=m[4], fmt=meta[1], series=meta[2],
                      cta=meta[3], needs=needs[1] if needs else "", todo=todo))

posts.sort(key=lambda p: p["date"])
expected = [START + dt.timedelta(days=i) for i in range(91)]
if [p["date"] for p in posts] != expected:
    errors.append(f"expected 91 consecutive days from {START}, got {len(posts)} posts")

def link(p):
    return f"[{p['title']}](<{p['folder']}/post.md>)"

cal = ["# Content calendar: Sep 28 – Dec 27, 2026", "",
       "Generated by `build_calendar.py`, so edit the post files, not this table.", "",
       "Needs: 🎥 face recording · 🖥️ screen recording · 📰 news check on the day · [RAM INPUT] real details from you", ""]
week = None
for p in posts:
    w = (p["date"] - START).days // 7 + 1
    if w != week:
        week = w
        end = START + dt.timedelta(days=7 * w - 1)
        cal += ["", f"## Week {w} · {START + dt.timedelta(days=7*(w-1)):%b %-d} – {end:%b %-d}", "",
                "| Date | Format | Series | Post | CTA | Needs |", "|---|---|---|---|---|---|"]
    fmt = p["fmt"].split(" (")[0]
    cal.append(f"| {p['date']:%a %b %-d} | {fmt} | {p['series']} | {link(p)} | {p['cta']} | {p['needs']} |")
(ROOT / "CALENDAR.md").write_text("\n".join(cal) + "\n")

rec = ["# Recording list", "",
       "Batch these on the weekend before each week. Generated by `build_calendar.py`.", "",
       "Tip: record all the face-to-camera lines for the week in one sitting (same outfit and light, so it looks like a series), then do the screen recordings as you work.", ""]
week = None
for p in posts:
    if not p["todo"]:
        continue
    w = (p["date"] - START).days // 7 + 1
    if w != week:
        week = w
        session = START + dt.timedelta(days=7 * (w - 1) - 1)
        rec += ["", f"## Week {w}: record by {session:%a %b %-d}", ""]
    rec.append(f"### {p['date']:%a %b %-d} · {link(p)}")
    rec += [f"- [ ] {t}" for t in p["todo"]] + [""]
(ROOT / "RECORDING.md").write_text("\n".join(rec) + "\n")

reels = sum("Reel" in p["fmt"] for p in posts)
print(f"{len(posts)} posts · {reels} Reels · {len(posts) - reels} carousels · "
      f"{sum('🎥' in p['needs'] for p in posts)} need face recording · "
      f"{sum('RAM INPUT' in p['needs'] for p in posts)} need RAM INPUT · "
      f"{sum('📰' in p['needs'] for p in posts)} news slots")
if errors:
    print("\n".join(errors))
    sys.exit(1)
